package com.kaibutsusama.stock.system.dao;

import com.kaibutsusama.stock.system.entity.TTradeAccount;

public interface TTradeAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade_account
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    int insert(TTradeAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade_account
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    int insertSelective(TTradeAccount record);
}