package com.kaibutsusama.stock.system.dao;

import com.kaibutsusama.stock.system.entity.TTradeUser;

public interface TTradeUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade_user
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    int insert(TTradeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade_user
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    int insertSelective(TTradeUser record);
}