// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockService.proto

package com.kaibutsusama.grpc.lib;

public interface StockServiceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StockServiceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
