// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockService.proto

package com.kaibutsusama.grpc.lib;

public interface StockServiceReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StockServiceReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
