package com.kaibutsusama.stock.system.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * 
 * t_trade_account
 *
 *
 * @mbg.generated Sat Aug 13 19:12:41 CST 2022
 */
public class TTradeAccount implements Serializable {
    /**
     * 主键标识
     */
    private Long id;

    /**
     */
    private Long userId;

    /**
     * 交易账号
     */
    private String accountNo;

    /**
     * 余额
     */
    private Long balance;

    /**
     * 账户组ID
     */
    private Long tradeGroupId;

    /**
     * 开户时间
     */
    private Date activeTime;

    /**
     * 状态(0:有效， 1：锁定， 2：禁用）
     */
    private Byte status;

    /**
     * 机构类型id
     */
    private String institutionTypeId;

    /**
     * 对应机构类型下的机构id
     */
    private Long institutionId;

    /**
     * 公司ID
     */
    private Long companyId;

    /**
     * 用户名称
     */
    private String userName;

    /**
     * 账户组名称
     */
    private String tradeGroupName;

    /**
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * 主键标识
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_account.id
     *
     * @param id the value for t_trade_account.id
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_account.userId
     *
     * @param userId the value for t_trade_account.userId
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * 交易账号
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_account.accountNo
     *
     * @param accountNo the value for t_trade_account.accountNo
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo == null ? null : accountNo.trim();
    }

    /**
     * 余额
     */
    public Long getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_account.balance
     *
     * @param balance the value for t_trade_account.balance
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    public void setBalance(Long balance) {
        this.balance = balance;
    }

    /**
     * 账户组ID
     */
    public Long getTradeGroupId() {
        return tradeGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_account.tradeGroupId
     *
     * @param tradeGroupId the value for t_trade_account.tradeGroupId
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    public void setTradeGroupId(Long tradeGroupId) {
        this.tradeGroupId = tradeGroupId;
    }

    /**
     * 开户时间
     */
    public Date getActiveTime() {
        return activeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_account.activeTime
     *
     * @param activeTime the value for t_trade_account.activeTime
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    public void setActiveTime(Date activeTime) {
        this.activeTime = activeTime;
    }

    /**
     * 状态(0:有效， 1：锁定， 2：禁用）
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_account.status
     *
     * @param status the value for t_trade_account.status
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * 机构类型id
     */
    public String getInstitutionTypeId() {
        return institutionTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_account.institutionTypeId
     *
     * @param institutionTypeId the value for t_trade_account.institutionTypeId
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    public void setInstitutionTypeId(String institutionTypeId) {
        this.institutionTypeId = institutionTypeId == null ? null : institutionTypeId.trim();
    }

    /**
     * 对应机构类型下的机构id
     */
    public Long getInstitutionId() {
        return institutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_account.institutionId
     *
     * @param institutionId the value for t_trade_account.institutionId
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    public void setInstitutionId(Long institutionId) {
        this.institutionId = institutionId;
    }

    /**
     * 公司ID
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_account.companyId
     *
     * @param companyId the value for t_trade_account.companyId
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * 用户名称
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_account.userName
     *
     * @param userName the value for t_trade_account.userName
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * 账户组名称
     */
    public String getTradeGroupName() {
        return tradeGroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_account.tradeGroupName
     *
     * @param tradeGroupName the value for t_trade_account.tradeGroupName
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    public void setTradeGroupName(String tradeGroupName) {
        this.tradeGroupName = tradeGroupName == null ? null : tradeGroupName.trim();
    }
}