package com.kaibutsusama.stock.system.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * 
 * t_trade_user
 *
 *
 * @mbg.generated Sat Aug 13 19:12:41 CST 2022
 */
public class TTradeUser implements Serializable {
    /**
     * 主键标识
     */
    private Long id;

    /**
     * 用户编号
     */
    private String userNo;

    /**
     * 用户名称
     */
    private String name;

    /**
     * 用户密码
     */
    private String userPwd;

    /**
     * 电话号码
     */
    private String phone;

    /**
     * 公司ID
     */
    private Long companyId;

    /**
     * 邮箱
     */
    private String email;

    /**
     * 地址
     */
    private String address;

    /**
     * 最近一次用户登陆IP
     */
    private String lastLoginIp;

    /**
     * 最近一次登陆时间
     */
    private Date lastLoginTime;

    /**
     * 状态(0:有效， 1：锁定， 2：禁用）
     */
    private Byte status;

    /**
     * 创建时间
     */
    private Date craeteTime;

    /**
     * 身份证
     */
    private String idcard;

    /**
     * 机构类型id
     */
    private String institutionTypeId;

    /**
     * 对应机构类型下的机构id
     */
    private Long institutionId;

    /**
     * 公司名称
     */
    private String companyName;

    /**
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * 主键标识
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_user.id
     *
     * @param id the value for t_trade_user.id
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 用户编号
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_user.userNo
     *
     * @param userNo the value for t_trade_user.userNo
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo == null ? null : userNo.trim();
    }

    /**
     * 用户名称
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_user.name
     *
     * @param name the value for t_trade_user.name
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 用户密码
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_user.userPwd
     *
     * @param userPwd the value for t_trade_user.userPwd
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * 电话号码
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_user.phone
     *
     * @param phone the value for t_trade_user.phone
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * 公司ID
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_user.companyId
     *
     * @param companyId the value for t_trade_user.companyId
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * 邮箱
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_user.email
     *
     * @param email the value for t_trade_user.email
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * 地址
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_user.address
     *
     * @param address the value for t_trade_user.address
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * 最近一次用户登陆IP
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_user.lastLoginIp
     *
     * @param lastLoginIp the value for t_trade_user.lastLoginIp
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
    }

    /**
     * 最近一次登陆时间
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_user.lastLoginTime
     *
     * @param lastLoginTime the value for t_trade_user.lastLoginTime
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * 状态(0:有效， 1：锁定， 2：禁用）
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_user.status
     *
     * @param status the value for t_trade_user.status
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * 创建时间
     */
    public Date getCraeteTime() {
        return craeteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_user.craeteTime
     *
     * @param craeteTime the value for t_trade_user.craeteTime
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    public void setCraeteTime(Date craeteTime) {
        this.craeteTime = craeteTime;
    }

    /**
     * 身份证
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_user.idcard
     *
     * @param idcard the value for t_trade_user.idcard
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * 机构类型id
     */
    public String getInstitutionTypeId() {
        return institutionTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_user.institutionTypeId
     *
     * @param institutionTypeId the value for t_trade_user.institutionTypeId
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    public void setInstitutionTypeId(String institutionTypeId) {
        this.institutionTypeId = institutionTypeId == null ? null : institutionTypeId.trim();
    }

    /**
     * 对应机构类型下的机构id
     */
    public Long getInstitutionId() {
        return institutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_user.institutionId
     *
     * @param institutionId the value for t_trade_user.institutionId
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    public void setInstitutionId(Long institutionId) {
        this.institutionId = institutionId;
    }

    /**
     * 公司名称
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_user.companyName
     *
     * @param companyName the value for t_trade_user.companyName
     *
     * @mbg.generated Sat Aug 13 19:12:41 CST 2022
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }
}